version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "org.apache.felix:maven-bundle-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.mycila:license-maven-plugin"
        update-types: ["version-update:semver-major"]